//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTest {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextSource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientTest.TextSource", typeof(TextSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 塒NG
        ///
        ///        ///IHDR??MＴ?sRGB?gAMA睆黙	pHYs??莖╠DATx^禳Q抦K抍夣??閍qt?AEY?0埯鼷鈋喳€?
        ///5硙&lt;Df??????鼉?
        ///?锬隐&apos;??裏3?垮????牽????吡唔w骟7瘅历?;?蠃线?/?怃F?q~鸞遢熥?&lt;8睨O????K?Zw?yw?€7?捩O靾?具溼硖軴?3?棺闉?鯚?}?鳲|T鴒39刁?壙蔑詆X鐈氓6踶敷収?痫?麱?o7?鏞X畸泰呒達?t篥P嗸潫z&apos;D箫黳縼7鼽飷呗o剧呻?dv瘰^泌匸?飋弌=n??}оt?瑊???觲夻?餱頪o?gOo倪懀a韄踔勘掼w闈櫩濄??濓糿g3揸熋哚?橕g麿錘O兖-n瀘龅?3讫鋙3煊瑉鉏酱嘀k狖〓??阚?2o嘤t齽O鯈矍︾燁骩w梓?贽茼]??輒挚笊]O綍冔絆8睑齐趛:+H漶4牴?顺?{j鵀??熽o?熿?檈?&gt;缈鷡哕楓熟毀?醒3?C饁?7`&apos;??幓z7?閛;?3?鏖€? [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string express_test {
            get {
                return ResourceManager.GetString("express_test", resourceCulture);
            }
        }
    }
}
